const token=localStorage.getItem("jobSkillToken");
if(!token) location.href="/login.html";
const headers={"Authorization":"Bearer "+token};
const $=id=>document.getElementById(id);
async function get(path){const r=await fetch("/api"+path,{headers});const d=await r.json();if(!r.ok){if(r.status===401||r.status===403){localStorage.clear();location.href="/login.html"}throw Error(d.error)}return d}
async function put(path,body){const r=await fetch("/api"+path,{method:"PUT",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function loadStats(){const d=await get("/admin/stats");$("usersCount").textContent=d.users;$("pendingCount").textContent=d.pending;$("approvedCount").textContent=d.approved;$("messageCount").textContent=d.unreadMessages}
async function loadApplications(){const d=await get("/admin/applications");$("applicationRows").innerHTML=d.applications.map(a=>`<tr><td><strong>${esc(a.first_name)} ${esc(a.last_name)}</strong><br><small>${esc(a.email)}</small></td><td>${esc(a.course_title)}</td><td>${esc(a.programme)}</td><td>${new Date(a.created_at+"Z").toLocaleDateString()}</td><td><span class="status ${a.status}">${a.status}</span></td><td><button class="action" onclick="review(${a.id})">${a.status==="pending"?"Review":"View"}</button></td></tr>`).join("")||'<tr><td colspan="6">No applications yet.</td></tr>'}
async function loadUsers(){const d=await get("/admin/users");$("userRows").innerHTML=d.users.map(u=>`<tr><td>${esc(u.first_name)} ${esc(u.last_name)}</td><td>${esc(u.email)}</td><td>${esc(u.phone||"—")}</td><td>${esc(u.account_type||"—")}</td><td>${u.application_count}</td><td>${new Date(u.created_at+"Z").toLocaleDateString()}</td></tr>`).join("")||'<tr><td colspan="6">No learners have registered yet.</td></tr>'}
async function loadMessages(){const d=await get("/admin/messages");$("messageList").innerHTML=d.messages.map(m=>`<article class="message"><strong>${esc(m.name)}</strong><small>${esc(m.email)} · ${new Date(m.created_at+"Z").toLocaleString()}</small><p>${esc(m.message)}</p>${m.status==="unread"?`<button class="action" onclick="markRead(${m.id})">Mark as read</button>`:"<small>Read</small>"}</article>`).join("")||"<p>No messages.</p>"}
async function loadAll(){try{await Promise.all([loadStats(),loadApplications(),loadUsers(),loadMessages()]);const me=await get("/auth/me");$("adminName").textContent=`${me.user.first_name} ${me.user.last_name}`}catch(e){alert(e.message)}}
async function review(id){const d=await get("/admin/applications");const a=d.applications.find(x=>x.id===id);if(!a)return;
$("modalContent").innerHTML=`<p class="eyebrow">APPLICATION #${a.id}</p><h2>${esc(a.first_name)} ${esc(a.last_name)}</h2><div class="detail-grid"><div class="detail"><small>Email</small><strong>${esc(a.email)}</strong></div><div class="detail"><small>Phone</small><strong>${esc(a.user_phone||a.phone||"—")}</strong></div><div class="detail"><small>Course</small><strong>${esc(a.course_title)}</strong></div><div class="detail"><small>Programme</small><strong>${esc(a.programme)}</strong></div><div class="detail"><small>Status</small><strong>${esc(a.status)}</strong></div><div class="detail"><small>Submitted</small><strong>${new Date(a.created_at+"Z").toLocaleString()}</strong></div></div><p><strong>Applicant's message</strong></p><p>${esc(a.message)}</p><label><strong>Administrator note</strong></label><textarea class="note" id="adminNote" placeholder="Optional message to the applicant...">${esc(a.admin_note||"")}</textarea>${a.status==="pending"?`<div class="decision"><button class="accept" onclick="decide(${a.id},'approved')">Accept Application</button><button class="reject" onclick="decide(${a.id},'rejected')">Reject Application</button></div>`:`<p style="margin-top:18px"><strong>Decision:</strong> ${esc(a.status)}${a.admin_note?` — ${esc(a.admin_note)}`:""}</p>`}`;
$("modal").classList.add("show")}
function closeModal(){$("modal").classList.remove("show")}
async function decide(id,status){try{await put(`/admin/applications/${id}/decision`,{status,adminNote:$("adminNote").value});closeModal();await loadAll();alert(`Application ${status}.`)}catch(e){alert(e.message)}}
async function markRead(id){try{await put(`/admin/messages/${id}/read`,{});loadAll()}catch(e){alert(e.message)}}
$("logout").onclick=()=>{localStorage.clear();location.href="/login.html"};
loadAll();
